### ISSUE TITLE
Unity?

### ISSUE THREAD

**Issue by Zyles** [averrin/mapgen#2]
Hi,

Amazing technology you have made.

I want to make a trading game based on a big voronoi map like this with cities, regions, weather, resources etc. This is truly amazing inspiration.

I was wondering if you know how to get this working in Unity? If you can use the DLL in Unity instead of having to convert project to C#?

Thanks.

**Comment by averrin** [comment]
My project use this parts: voronoi generator (i know c# has implementation, and i think unity itself has it too), libnoise (perlin noise libs is pretty common in any language), A* path finder (every game engine has it) and sfml for graphics (unity). So you needn't use any libs from my project.

**Comment by Zyles** [comment]
I have read a lot about it and understand all parts in **theory** but it is hard to implement in **practice** if you are not a very good programmer. To generate a map that looks and work realistic and not just noise. It is like a puzzle, you have all the parts and the image, but it is still hard to finish.

There are a lot of problems that need to be solved:

- How to place cities not too close to each other
- How to divide the map into regions, multiple voronoi grids in one region (so a city controls a region around it)
- How to have smaller provinces (one voronoi grid that knows it belongs to a region) in the bigger regions
- Climate, temperature (heat maps), resource generation in grids.

Are you using Delaunay Triangulation? Because I read there are problems with A* pathfinding and voronoi maps.

You should make an asset for Unity that renders this type of terrain with pathfinding support. I would buy it!

I want to make a game that has a map like Civilization, but is not hex-grid (voronoi looks more natural).

**Comment by averrin** [comment]
I have some articles exact about this topics, but its in Russian, because im not so good in English=( But you can find some information [here](http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/) and [here](https://azgaar.wordpress.com/)

**Comment by Zyles** [comment]
Yes I have read them. But this is VERY HARD!

You **really** should convert this map generator to C# Unity! I am making a transport game but I can't do a map like this. :(

I watched your Youtube video. It is amazing!

**Comment by averrin** [comment]
Yeah, unity!
https://streamable.com/n721g
