### ISSUE TITLE
imgui-sfml build error

### ISSUE THREAD

**Issue by spacehamster** [averrin/mapgen#4]
imgui-sfml requires the contents of imgui-sfml/imconfig-SFML.h to be copied into imgui/imconfig.h. 
Can this be done automatically in cmake?

**Comment by averrin** [comment]
IIRC its one time command like `cat ./include/imgui-sfml/imconfig-SFML.h >> ./include/imgui/imconfig.h`. Yeah, i think its possible but it needs some guard to do it only once but not every cmake run.

**Comment by spacehamster** [comment]
I got it working #7
